### PR TITLE
Now Different color can be given to Smilies.

### PR DESCRIPTION
**Pull request by harsh159357**
Now Different color can be given to Smilies. Fixed Issue No.9 https://github.com/sujithkanna/SmileyRating/issues/9 (distinct smilies color #9). But it will still need some more tweaking like setting the color in while declaring SmileyRating in the layout file.

### CODE REVIEW

**Comment by dinesh3367** [comment]
how can i get this to my app that i had developed ?? i am still getting single color on the smileys that were the case in old app

**Comment by harsh159357** [comment]
@dinesh3367 Yes there are different colors and you can see them here 

https://github.com/harsh159357/SmileyRating/blob/master/smilerating/src/main/java/com/hsalf/smilerating/SmileRating.java (Line no 39 -44 )

**Comment by dinesh3367** [comment]
how should i update my app now ??

i am still seeing single color for all smiley except the angry one.

i am integrating the library using the following comment in build.gradle
compile 'com.github.sujithkanna:smileyrating:1.6.8'

**Comment by harsh159357** [comment]
@dinesh3367 you should use this library as a module 
https://stackoverflow.com/questions/20377591/how-to-use-a-library-project-in-android-studio
(Main Benefit you can customize or even improve the Library according to your need when you are using it as a module)

Right now the 1.6.8 version of smiley rating does not include(smiley with different colors) those changes are there on master branch of smileyrating but the owner of the library hasn't publish those changes cuz there is still more tweaking needs to be done.

But if you want smiley with different color right now you can use it as a module and you can customize the colors present in https://github.com/harsh159357/SmileyRating/blob/master/smilerating/src/main/java/com/hsalf/smilerating/SmileRating.java  (Line No 39 - 44)

(Make Sure use this library as module or wait for the next release of the library)

**Comment by dinesh3367** [comment]
perfect harsha.
thanks a lot for your support.
It works Great..!!

**Pull request merged**
